// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

package com.spw.proto;

/**
 * <pre>
 *定义接口
 * </pre>
 *
 * Protobuf service {@code proto.HelloService}
 */
public  abstract class HelloService
    implements com.google.protobuf.Service {
  protected HelloService() {}

  public interface Interface {
    /**
     * <pre>
     *一个简单的rpc
     * </pre>
     *
     * <code>rpc HelloWorld(.proto.HelloRequest) returns (.proto.HelloResponse);</code>
     */
    public abstract void helloWorld(
        com.google.protobuf.RpcController controller,
        com.spw.proto.HelloRequest request,
        com.google.protobuf.RpcCallback<com.spw.proto.HelloResponse> done);

    /**
     * <pre>
     *一个服务器端流式rpc
     * </pre>
     *
     * <code>rpc HelloWorldServerStream(.proto.HelloRequest) returns (stream .proto.HelloResponse);</code>
     */
    public abstract void helloWorldServerStream(
        com.google.protobuf.RpcController controller,
        com.spw.proto.HelloRequest request,
        com.google.protobuf.RpcCallback<com.spw.proto.HelloResponse> done);

    /**
     * <pre>
     *一个客户端流式rpc
     * </pre>
     *
     * <code>rpc HelloWorldClientStream(stream .proto.HelloRequest) returns (.proto.HelloResponse);</code>
     */
    public abstract void helloWorldClientStream(
        com.google.protobuf.RpcController controller,
        com.spw.proto.HelloRequest request,
        com.google.protobuf.RpcCallback<com.spw.proto.HelloResponse> done);

    /**
     * <pre>
     *一个客户端和服务器端双向流式rpc
     * </pre>
     *
     * <code>rpc HelloWorldClientAndServerStream(stream .proto.HelloRequest) returns (stream .proto.HelloResponse);</code>
     */
    public abstract void helloWorldClientAndServerStream(
        com.google.protobuf.RpcController controller,
        com.spw.proto.HelloRequest request,
        com.google.protobuf.RpcCallback<com.spw.proto.HelloResponse> done);

  }

  public static com.google.protobuf.Service newReflectiveService(
      final Interface impl) {
    return new HelloService() {
      @java.lang.Override
      public  void helloWorld(
          com.google.protobuf.RpcController controller,
          com.spw.proto.HelloRequest request,
          com.google.protobuf.RpcCallback<com.spw.proto.HelloResponse> done) {
        impl.helloWorld(controller, request, done);
      }

      @java.lang.Override
      public  void helloWorldServerStream(
          com.google.protobuf.RpcController controller,
          com.spw.proto.HelloRequest request,
          com.google.protobuf.RpcCallback<com.spw.proto.HelloResponse> done) {
        impl.helloWorldServerStream(controller, request, done);
      }

      @java.lang.Override
      public  void helloWorldClientStream(
          com.google.protobuf.RpcController controller,
          com.spw.proto.HelloRequest request,
          com.google.protobuf.RpcCallback<com.spw.proto.HelloResponse> done) {
        impl.helloWorldClientStream(controller, request, done);
      }

      @java.lang.Override
      public  void helloWorldClientAndServerStream(
          com.google.protobuf.RpcController controller,
          com.spw.proto.HelloRequest request,
          com.google.protobuf.RpcCallback<com.spw.proto.HelloResponse> done) {
        impl.helloWorldClientAndServerStream(controller, request, done);
      }

    };
  }

  public static com.google.protobuf.BlockingService
      newReflectiveBlockingService(final BlockingInterface impl) {
    return new com.google.protobuf.BlockingService() {
      public final com.google.protobuf.Descriptors.ServiceDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }

      public final com.google.protobuf.Message callBlockingMethod(
          com.google.protobuf.Descriptors.MethodDescriptor method,
          com.google.protobuf.RpcController controller,
          com.google.protobuf.Message request)
          throws com.google.protobuf.ServiceException {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.callBlockingMethod() given method descriptor for " +
            "wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return impl.helloWorld(controller, (com.spw.proto.HelloRequest)request);
          case 1:
            return impl.helloWorldServerStream(controller, (com.spw.proto.HelloRequest)request);
          case 2:
            return impl.helloWorldClientStream(controller, (com.spw.proto.HelloRequest)request);
          case 3:
            return impl.helloWorldClientAndServerStream(controller, (com.spw.proto.HelloRequest)request);
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getRequestPrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getRequestPrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return com.spw.proto.HelloRequest.getDefaultInstance();
          case 1:
            return com.spw.proto.HelloRequest.getDefaultInstance();
          case 2:
            return com.spw.proto.HelloRequest.getDefaultInstance();
          case 3:
            return com.spw.proto.HelloRequest.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getResponsePrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getResponsePrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return com.spw.proto.HelloResponse.getDefaultInstance();
          case 1:
            return com.spw.proto.HelloResponse.getDefaultInstance();
          case 2:
            return com.spw.proto.HelloResponse.getDefaultInstance();
          case 3:
            return com.spw.proto.HelloResponse.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

    };
  }

  /**
   * <pre>
   *一个简单的rpc
   * </pre>
   *
   * <code>rpc HelloWorld(.proto.HelloRequest) returns (.proto.HelloResponse);</code>
   */
  public abstract void helloWorld(
      com.google.protobuf.RpcController controller,
      com.spw.proto.HelloRequest request,
      com.google.protobuf.RpcCallback<com.spw.proto.HelloResponse> done);

  /**
   * <pre>
   *一个服务器端流式rpc
   * </pre>
   *
   * <code>rpc HelloWorldServerStream(.proto.HelloRequest) returns (stream .proto.HelloResponse);</code>
   */
  public abstract void helloWorldServerStream(
      com.google.protobuf.RpcController controller,
      com.spw.proto.HelloRequest request,
      com.google.protobuf.RpcCallback<com.spw.proto.HelloResponse> done);

  /**
   * <pre>
   *一个客户端流式rpc
   * </pre>
   *
   * <code>rpc HelloWorldClientStream(stream .proto.HelloRequest) returns (.proto.HelloResponse);</code>
   */
  public abstract void helloWorldClientStream(
      com.google.protobuf.RpcController controller,
      com.spw.proto.HelloRequest request,
      com.google.protobuf.RpcCallback<com.spw.proto.HelloResponse> done);

  /**
   * <pre>
   *一个客户端和服务器端双向流式rpc
   * </pre>
   *
   * <code>rpc HelloWorldClientAndServerStream(stream .proto.HelloRequest) returns (stream .proto.HelloResponse);</code>
   */
  public abstract void helloWorldClientAndServerStream(
      com.google.protobuf.RpcController controller,
      com.spw.proto.HelloRequest request,
      com.google.protobuf.RpcCallback<com.spw.proto.HelloResponse> done);

  public static final
      com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptor() {
    return com.spw.proto.HelloWorldProto.getDescriptor().getServices().get(0);
  }
  public final com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }

  public final void callMethod(
      com.google.protobuf.Descriptors.MethodDescriptor method,
      com.google.protobuf.RpcController controller,
      com.google.protobuf.Message request,
      com.google.protobuf.RpcCallback<
        com.google.protobuf.Message> done) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.callMethod() given method descriptor for wrong " +
        "service type.");
    }
    switch(method.getIndex()) {
      case 0:
        this.helloWorld(controller, (com.spw.proto.HelloRequest)request,
          com.google.protobuf.RpcUtil.<com.spw.proto.HelloResponse>specializeCallback(
            done));
        return;
      case 1:
        this.helloWorldServerStream(controller, (com.spw.proto.HelloRequest)request,
          com.google.protobuf.RpcUtil.<com.spw.proto.HelloResponse>specializeCallback(
            done));
        return;
      case 2:
        this.helloWorldClientStream(controller, (com.spw.proto.HelloRequest)request,
          com.google.protobuf.RpcUtil.<com.spw.proto.HelloResponse>specializeCallback(
            done));
        return;
      case 3:
        this.helloWorldClientAndServerStream(controller, (com.spw.proto.HelloRequest)request,
          com.google.protobuf.RpcUtil.<com.spw.proto.HelloResponse>specializeCallback(
            done));
        return;
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getRequestPrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getRequestPrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return com.spw.proto.HelloRequest.getDefaultInstance();
      case 1:
        return com.spw.proto.HelloRequest.getDefaultInstance();
      case 2:
        return com.spw.proto.HelloRequest.getDefaultInstance();
      case 3:
        return com.spw.proto.HelloRequest.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getResponsePrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getResponsePrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return com.spw.proto.HelloResponse.getDefaultInstance();
      case 1:
        return com.spw.proto.HelloResponse.getDefaultInstance();
      case 2:
        return com.spw.proto.HelloResponse.getDefaultInstance();
      case 3:
        return com.spw.proto.HelloResponse.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public static Stub newStub(
      com.google.protobuf.RpcChannel channel) {
    return new Stub(channel);
  }

  public static final class Stub extends com.spw.proto.HelloService implements Interface {
    private Stub(com.google.protobuf.RpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.RpcChannel channel;

    public com.google.protobuf.RpcChannel getChannel() {
      return channel;
    }

    public  void helloWorld(
        com.google.protobuf.RpcController controller,
        com.spw.proto.HelloRequest request,
        com.google.protobuf.RpcCallback<com.spw.proto.HelloResponse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        com.spw.proto.HelloResponse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          com.spw.proto.HelloResponse.class,
          com.spw.proto.HelloResponse.getDefaultInstance()));
    }

    public  void helloWorldServerStream(
        com.google.protobuf.RpcController controller,
        com.spw.proto.HelloRequest request,
        com.google.protobuf.RpcCallback<com.spw.proto.HelloResponse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(1),
        controller,
        request,
        com.spw.proto.HelloResponse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          com.spw.proto.HelloResponse.class,
          com.spw.proto.HelloResponse.getDefaultInstance()));
    }

    public  void helloWorldClientStream(
        com.google.protobuf.RpcController controller,
        com.spw.proto.HelloRequest request,
        com.google.protobuf.RpcCallback<com.spw.proto.HelloResponse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(2),
        controller,
        request,
        com.spw.proto.HelloResponse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          com.spw.proto.HelloResponse.class,
          com.spw.proto.HelloResponse.getDefaultInstance()));
    }

    public  void helloWorldClientAndServerStream(
        com.google.protobuf.RpcController controller,
        com.spw.proto.HelloRequest request,
        com.google.protobuf.RpcCallback<com.spw.proto.HelloResponse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(3),
        controller,
        request,
        com.spw.proto.HelloResponse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          com.spw.proto.HelloResponse.class,
          com.spw.proto.HelloResponse.getDefaultInstance()));
    }
  }

  public static BlockingInterface newBlockingStub(
      com.google.protobuf.BlockingRpcChannel channel) {
    return new BlockingStub(channel);
  }

  public interface BlockingInterface {
    public com.spw.proto.HelloResponse helloWorld(
        com.google.protobuf.RpcController controller,
        com.spw.proto.HelloRequest request)
        throws com.google.protobuf.ServiceException;

    public com.spw.proto.HelloResponse helloWorldServerStream(
        com.google.protobuf.RpcController controller,
        com.spw.proto.HelloRequest request)
        throws com.google.protobuf.ServiceException;

    public com.spw.proto.HelloResponse helloWorldClientStream(
        com.google.protobuf.RpcController controller,
        com.spw.proto.HelloRequest request)
        throws com.google.protobuf.ServiceException;

    public com.spw.proto.HelloResponse helloWorldClientAndServerStream(
        com.google.protobuf.RpcController controller,
        com.spw.proto.HelloRequest request)
        throws com.google.protobuf.ServiceException;
  }

  private static final class BlockingStub implements BlockingInterface {
    private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.BlockingRpcChannel channel;

    public com.spw.proto.HelloResponse helloWorld(
        com.google.protobuf.RpcController controller,
        com.spw.proto.HelloRequest request)
        throws com.google.protobuf.ServiceException {
      return (com.spw.proto.HelloResponse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        com.spw.proto.HelloResponse.getDefaultInstance());
    }


    public com.spw.proto.HelloResponse helloWorldServerStream(
        com.google.protobuf.RpcController controller,
        com.spw.proto.HelloRequest request)
        throws com.google.protobuf.ServiceException {
      return (com.spw.proto.HelloResponse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(1),
        controller,
        request,
        com.spw.proto.HelloResponse.getDefaultInstance());
    }


    public com.spw.proto.HelloResponse helloWorldClientStream(
        com.google.protobuf.RpcController controller,
        com.spw.proto.HelloRequest request)
        throws com.google.protobuf.ServiceException {
      return (com.spw.proto.HelloResponse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(2),
        controller,
        request,
        com.spw.proto.HelloResponse.getDefaultInstance());
    }


    public com.spw.proto.HelloResponse helloWorldClientAndServerStream(
        com.google.protobuf.RpcController controller,
        com.spw.proto.HelloRequest request)
        throws com.google.protobuf.ServiceException {
      return (com.spw.proto.HelloResponse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(3),
        controller,
        request,
        com.spw.proto.HelloResponse.getDefaultInstance());
    }

  }

  // @@protoc_insertion_point(class_scope:proto.HelloService)
}

