// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package com.spw.proto2;

/**
 * Protobuf type {@code trojan.api.GetTrafficResponse}
 */
public  final class GetTrafficResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:trojan.api.GetTrafficResponse)
    GetTrafficResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetTrafficResponse.newBuilder() to construct.
  private GetTrafficResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetTrafficResponse() {
    success_ = false;
    info_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetTrafficResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            success_ = input.readBool();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            info_ = s;
            break;
          }
          case 26: {
            com.spw.proto2.Traffic.Builder subBuilder = null;
            if (trafficTotal_ != null) {
              subBuilder = trafficTotal_.toBuilder();
            }
            trafficTotal_ = input.readMessage(com.spw.proto2.Traffic.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(trafficTotal_);
              trafficTotal_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            com.spw.proto2.Speed.Builder subBuilder = null;
            if (speedCurrent_ != null) {
              subBuilder = speedCurrent_.toBuilder();
            }
            speedCurrent_ = input.readMessage(com.spw.proto2.Speed.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(speedCurrent_);
              speedCurrent_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.spw.proto2.HelloWorldProto2.internal_static_trojan_api_GetTrafficResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.spw.proto2.HelloWorldProto2.internal_static_trojan_api_GetTrafficResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.spw.proto2.GetTrafficResponse.class, com.spw.proto2.GetTrafficResponse.Builder.class);
  }

  public static final int SUCCESS_FIELD_NUMBER = 1;
  private boolean success_;
  /**
   * <code>bool success = 1;</code>
   */
  public boolean getSuccess() {
    return success_;
  }

  public static final int INFO_FIELD_NUMBER = 2;
  private volatile java.lang.Object info_;
  /**
   * <code>string info = 2;</code>
   */
  public java.lang.String getInfo() {
    java.lang.Object ref = info_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      info_ = s;
      return s;
    }
  }
  /**
   * <code>string info = 2;</code>
   */
  public com.google.protobuf.ByteString
      getInfoBytes() {
    java.lang.Object ref = info_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      info_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TRAFFIC_TOTAL_FIELD_NUMBER = 3;
  private com.spw.proto2.Traffic trafficTotal_;
  /**
   * <code>.trojan.api.Traffic traffic_total = 3;</code>
   */
  public boolean hasTrafficTotal() {
    return trafficTotal_ != null;
  }
  /**
   * <code>.trojan.api.Traffic traffic_total = 3;</code>
   */
  public com.spw.proto2.Traffic getTrafficTotal() {
    return trafficTotal_ == null ? com.spw.proto2.Traffic.getDefaultInstance() : trafficTotal_;
  }
  /**
   * <code>.trojan.api.Traffic traffic_total = 3;</code>
   */
  public com.spw.proto2.TrafficOrBuilder getTrafficTotalOrBuilder() {
    return getTrafficTotal();
  }

  public static final int SPEED_CURRENT_FIELD_NUMBER = 4;
  private com.spw.proto2.Speed speedCurrent_;
  /**
   * <code>.trojan.api.Speed speed_current = 4;</code>
   */
  public boolean hasSpeedCurrent() {
    return speedCurrent_ != null;
  }
  /**
   * <code>.trojan.api.Speed speed_current = 4;</code>
   */
  public com.spw.proto2.Speed getSpeedCurrent() {
    return speedCurrent_ == null ? com.spw.proto2.Speed.getDefaultInstance() : speedCurrent_;
  }
  /**
   * <code>.trojan.api.Speed speed_current = 4;</code>
   */
  public com.spw.proto2.SpeedOrBuilder getSpeedCurrentOrBuilder() {
    return getSpeedCurrent();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (success_ != false) {
      output.writeBool(1, success_);
    }
    if (!getInfoBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, info_);
    }
    if (trafficTotal_ != null) {
      output.writeMessage(3, getTrafficTotal());
    }
    if (speedCurrent_ != null) {
      output.writeMessage(4, getSpeedCurrent());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (success_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, success_);
    }
    if (!getInfoBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, info_);
    }
    if (trafficTotal_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getTrafficTotal());
    }
    if (speedCurrent_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getSpeedCurrent());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.spw.proto2.GetTrafficResponse)) {
      return super.equals(obj);
    }
    com.spw.proto2.GetTrafficResponse other = (com.spw.proto2.GetTrafficResponse) obj;

    boolean result = true;
    result = result && (getSuccess()
        == other.getSuccess());
    result = result && getInfo()
        .equals(other.getInfo());
    result = result && (hasTrafficTotal() == other.hasTrafficTotal());
    if (hasTrafficTotal()) {
      result = result && getTrafficTotal()
          .equals(other.getTrafficTotal());
    }
    result = result && (hasSpeedCurrent() == other.hasSpeedCurrent());
    if (hasSpeedCurrent()) {
      result = result && getSpeedCurrent()
          .equals(other.getSpeedCurrent());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSuccess());
    hash = (37 * hash) + INFO_FIELD_NUMBER;
    hash = (53 * hash) + getInfo().hashCode();
    if (hasTrafficTotal()) {
      hash = (37 * hash) + TRAFFIC_TOTAL_FIELD_NUMBER;
      hash = (53 * hash) + getTrafficTotal().hashCode();
    }
    if (hasSpeedCurrent()) {
      hash = (37 * hash) + SPEED_CURRENT_FIELD_NUMBER;
      hash = (53 * hash) + getSpeedCurrent().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.spw.proto2.GetTrafficResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.spw.proto2.GetTrafficResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.spw.proto2.GetTrafficResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.spw.proto2.GetTrafficResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.spw.proto2.GetTrafficResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.spw.proto2.GetTrafficResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.spw.proto2.GetTrafficResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.spw.proto2.GetTrafficResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.spw.proto2.GetTrafficResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.spw.proto2.GetTrafficResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.spw.proto2.GetTrafficResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.spw.proto2.GetTrafficResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.spw.proto2.GetTrafficResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code trojan.api.GetTrafficResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:trojan.api.GetTrafficResponse)
      com.spw.proto2.GetTrafficResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.spw.proto2.HelloWorldProto2.internal_static_trojan_api_GetTrafficResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.spw.proto2.HelloWorldProto2.internal_static_trojan_api_GetTrafficResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.spw.proto2.GetTrafficResponse.class, com.spw.proto2.GetTrafficResponse.Builder.class);
    }

    // Construct using com.spw.proto2.GetTrafficResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      success_ = false;

      info_ = "";

      if (trafficTotalBuilder_ == null) {
        trafficTotal_ = null;
      } else {
        trafficTotal_ = null;
        trafficTotalBuilder_ = null;
      }
      if (speedCurrentBuilder_ == null) {
        speedCurrent_ = null;
      } else {
        speedCurrent_ = null;
        speedCurrentBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.spw.proto2.HelloWorldProto2.internal_static_trojan_api_GetTrafficResponse_descriptor;
    }

    public com.spw.proto2.GetTrafficResponse getDefaultInstanceForType() {
      return com.spw.proto2.GetTrafficResponse.getDefaultInstance();
    }

    public com.spw.proto2.GetTrafficResponse build() {
      com.spw.proto2.GetTrafficResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.spw.proto2.GetTrafficResponse buildPartial() {
      com.spw.proto2.GetTrafficResponse result = new com.spw.proto2.GetTrafficResponse(this);
      result.success_ = success_;
      result.info_ = info_;
      if (trafficTotalBuilder_ == null) {
        result.trafficTotal_ = trafficTotal_;
      } else {
        result.trafficTotal_ = trafficTotalBuilder_.build();
      }
      if (speedCurrentBuilder_ == null) {
        result.speedCurrent_ = speedCurrent_;
      } else {
        result.speedCurrent_ = speedCurrentBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.spw.proto2.GetTrafficResponse) {
        return mergeFrom((com.spw.proto2.GetTrafficResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.spw.proto2.GetTrafficResponse other) {
      if (other == com.spw.proto2.GetTrafficResponse.getDefaultInstance()) return this;
      if (other.getSuccess() != false) {
        setSuccess(other.getSuccess());
      }
      if (!other.getInfo().isEmpty()) {
        info_ = other.info_;
        onChanged();
      }
      if (other.hasTrafficTotal()) {
        mergeTrafficTotal(other.getTrafficTotal());
      }
      if (other.hasSpeedCurrent()) {
        mergeSpeedCurrent(other.getSpeedCurrent());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.spw.proto2.GetTrafficResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.spw.proto2.GetTrafficResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private boolean success_ ;
    /**
     * <code>bool success = 1;</code>
     */
    public boolean getSuccess() {
      return success_;
    }
    /**
     * <code>bool success = 1;</code>
     */
    public Builder setSuccess(boolean value) {
      
      success_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool success = 1;</code>
     */
    public Builder clearSuccess() {
      
      success_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object info_ = "";
    /**
     * <code>string info = 2;</code>
     */
    public java.lang.String getInfo() {
      java.lang.Object ref = info_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        info_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string info = 2;</code>
     */
    public com.google.protobuf.ByteString
        getInfoBytes() {
      java.lang.Object ref = info_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        info_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string info = 2;</code>
     */
    public Builder setInfo(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      info_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string info = 2;</code>
     */
    public Builder clearInfo() {
      
      info_ = getDefaultInstance().getInfo();
      onChanged();
      return this;
    }
    /**
     * <code>string info = 2;</code>
     */
    public Builder setInfoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      info_ = value;
      onChanged();
      return this;
    }

    private com.spw.proto2.Traffic trafficTotal_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.spw.proto2.Traffic, com.spw.proto2.Traffic.Builder, com.spw.proto2.TrafficOrBuilder> trafficTotalBuilder_;
    /**
     * <code>.trojan.api.Traffic traffic_total = 3;</code>
     */
    public boolean hasTrafficTotal() {
      return trafficTotalBuilder_ != null || trafficTotal_ != null;
    }
    /**
     * <code>.trojan.api.Traffic traffic_total = 3;</code>
     */
    public com.spw.proto2.Traffic getTrafficTotal() {
      if (trafficTotalBuilder_ == null) {
        return trafficTotal_ == null ? com.spw.proto2.Traffic.getDefaultInstance() : trafficTotal_;
      } else {
        return trafficTotalBuilder_.getMessage();
      }
    }
    /**
     * <code>.trojan.api.Traffic traffic_total = 3;</code>
     */
    public Builder setTrafficTotal(com.spw.proto2.Traffic value) {
      if (trafficTotalBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        trafficTotal_ = value;
        onChanged();
      } else {
        trafficTotalBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.trojan.api.Traffic traffic_total = 3;</code>
     */
    public Builder setTrafficTotal(
        com.spw.proto2.Traffic.Builder builderForValue) {
      if (trafficTotalBuilder_ == null) {
        trafficTotal_ = builderForValue.build();
        onChanged();
      } else {
        trafficTotalBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.trojan.api.Traffic traffic_total = 3;</code>
     */
    public Builder mergeTrafficTotal(com.spw.proto2.Traffic value) {
      if (trafficTotalBuilder_ == null) {
        if (trafficTotal_ != null) {
          trafficTotal_ =
            com.spw.proto2.Traffic.newBuilder(trafficTotal_).mergeFrom(value).buildPartial();
        } else {
          trafficTotal_ = value;
        }
        onChanged();
      } else {
        trafficTotalBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.trojan.api.Traffic traffic_total = 3;</code>
     */
    public Builder clearTrafficTotal() {
      if (trafficTotalBuilder_ == null) {
        trafficTotal_ = null;
        onChanged();
      } else {
        trafficTotal_ = null;
        trafficTotalBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.trojan.api.Traffic traffic_total = 3;</code>
     */
    public com.spw.proto2.Traffic.Builder getTrafficTotalBuilder() {
      
      onChanged();
      return getTrafficTotalFieldBuilder().getBuilder();
    }
    /**
     * <code>.trojan.api.Traffic traffic_total = 3;</code>
     */
    public com.spw.proto2.TrafficOrBuilder getTrafficTotalOrBuilder() {
      if (trafficTotalBuilder_ != null) {
        return trafficTotalBuilder_.getMessageOrBuilder();
      } else {
        return trafficTotal_ == null ?
            com.spw.proto2.Traffic.getDefaultInstance() : trafficTotal_;
      }
    }
    /**
     * <code>.trojan.api.Traffic traffic_total = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.spw.proto2.Traffic, com.spw.proto2.Traffic.Builder, com.spw.proto2.TrafficOrBuilder> 
        getTrafficTotalFieldBuilder() {
      if (trafficTotalBuilder_ == null) {
        trafficTotalBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.spw.proto2.Traffic, com.spw.proto2.Traffic.Builder, com.spw.proto2.TrafficOrBuilder>(
                getTrafficTotal(),
                getParentForChildren(),
                isClean());
        trafficTotal_ = null;
      }
      return trafficTotalBuilder_;
    }

    private com.spw.proto2.Speed speedCurrent_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.spw.proto2.Speed, com.spw.proto2.Speed.Builder, com.spw.proto2.SpeedOrBuilder> speedCurrentBuilder_;
    /**
     * <code>.trojan.api.Speed speed_current = 4;</code>
     */
    public boolean hasSpeedCurrent() {
      return speedCurrentBuilder_ != null || speedCurrent_ != null;
    }
    /**
     * <code>.trojan.api.Speed speed_current = 4;</code>
     */
    public com.spw.proto2.Speed getSpeedCurrent() {
      if (speedCurrentBuilder_ == null) {
        return speedCurrent_ == null ? com.spw.proto2.Speed.getDefaultInstance() : speedCurrent_;
      } else {
        return speedCurrentBuilder_.getMessage();
      }
    }
    /**
     * <code>.trojan.api.Speed speed_current = 4;</code>
     */
    public Builder setSpeedCurrent(com.spw.proto2.Speed value) {
      if (speedCurrentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        speedCurrent_ = value;
        onChanged();
      } else {
        speedCurrentBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.trojan.api.Speed speed_current = 4;</code>
     */
    public Builder setSpeedCurrent(
        com.spw.proto2.Speed.Builder builderForValue) {
      if (speedCurrentBuilder_ == null) {
        speedCurrent_ = builderForValue.build();
        onChanged();
      } else {
        speedCurrentBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.trojan.api.Speed speed_current = 4;</code>
     */
    public Builder mergeSpeedCurrent(com.spw.proto2.Speed value) {
      if (speedCurrentBuilder_ == null) {
        if (speedCurrent_ != null) {
          speedCurrent_ =
            com.spw.proto2.Speed.newBuilder(speedCurrent_).mergeFrom(value).buildPartial();
        } else {
          speedCurrent_ = value;
        }
        onChanged();
      } else {
        speedCurrentBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.trojan.api.Speed speed_current = 4;</code>
     */
    public Builder clearSpeedCurrent() {
      if (speedCurrentBuilder_ == null) {
        speedCurrent_ = null;
        onChanged();
      } else {
        speedCurrent_ = null;
        speedCurrentBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.trojan.api.Speed speed_current = 4;</code>
     */
    public com.spw.proto2.Speed.Builder getSpeedCurrentBuilder() {
      
      onChanged();
      return getSpeedCurrentFieldBuilder().getBuilder();
    }
    /**
     * <code>.trojan.api.Speed speed_current = 4;</code>
     */
    public com.spw.proto2.SpeedOrBuilder getSpeedCurrentOrBuilder() {
      if (speedCurrentBuilder_ != null) {
        return speedCurrentBuilder_.getMessageOrBuilder();
      } else {
        return speedCurrent_ == null ?
            com.spw.proto2.Speed.getDefaultInstance() : speedCurrent_;
      }
    }
    /**
     * <code>.trojan.api.Speed speed_current = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.spw.proto2.Speed, com.spw.proto2.Speed.Builder, com.spw.proto2.SpeedOrBuilder> 
        getSpeedCurrentFieldBuilder() {
      if (speedCurrentBuilder_ == null) {
        speedCurrentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.spw.proto2.Speed, com.spw.proto2.Speed.Builder, com.spw.proto2.SpeedOrBuilder>(
                getSpeedCurrent(),
                getParentForChildren(),
                isClean());
        speedCurrent_ = null;
      }
      return speedCurrentBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:trojan.api.GetTrafficResponse)
  }

  // @@protoc_insertion_point(class_scope:trojan.api.GetTrafficResponse)
  private static final com.spw.proto2.GetTrafficResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.spw.proto2.GetTrafficResponse();
  }

  public static com.spw.proto2.GetTrafficResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetTrafficResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetTrafficResponse>() {
    public GetTrafficResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetTrafficResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetTrafficResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetTrafficResponse> getParserForType() {
    return PARSER;
  }

  public com.spw.proto2.GetTrafficResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

