// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package com.spw.proto2;

public interface GetTrafficRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:trojan.api.GetTrafficRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.trojan.api.User user = 1;</code>
   */
  boolean hasUser();
  /**
   * <code>.trojan.api.User user = 1;</code>
   */
  com.spw.proto2.User getUser();
  /**
   * <code>.trojan.api.User user = 1;</code>
   */
  com.spw.proto2.UserOrBuilder getUserOrBuilder();
}
