// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package com.spw.proto2;

public interface GetTrafficResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:trojan.api.GetTrafficResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   */
  boolean getSuccess();

  /**
   * <code>string info = 2;</code>
   */
  java.lang.String getInfo();
  /**
   * <code>string info = 2;</code>
   */
  com.google.protobuf.ByteString
      getInfoBytes();

  /**
   * <code>.trojan.api.Traffic traffic_total = 3;</code>
   */
  boolean hasTrafficTotal();
  /**
   * <code>.trojan.api.Traffic traffic_total = 3;</code>
   */
  com.spw.proto2.Traffic getTrafficTotal();
  /**
   * <code>.trojan.api.Traffic traffic_total = 3;</code>
   */
  com.spw.proto2.TrafficOrBuilder getTrafficTotalOrBuilder();

  /**
   * <code>.trojan.api.Speed speed_current = 4;</code>
   */
  boolean hasSpeedCurrent();
  /**
   * <code>.trojan.api.Speed speed_current = 4;</code>
   */
  com.spw.proto2.Speed getSpeedCurrent();
  /**
   * <code>.trojan.api.Speed speed_current = 4;</code>
   */
  com.spw.proto2.SpeedOrBuilder getSpeedCurrentOrBuilder();
}
