// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package com.spw.proto2;

public final class HelloWorldProto2 {
  private HelloWorldProto2() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_trojan_api_Traffic_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_trojan_api_Traffic_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_trojan_api_Speed_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_trojan_api_Speed_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_trojan_api_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_trojan_api_User_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_trojan_api_UserStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_trojan_api_UserStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_trojan_api_GetTrafficRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_trojan_api_GetTrafficRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_trojan_api_GetTrafficResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_trojan_api_GetTrafficResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_trojan_api_ListUsersRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_trojan_api_ListUsersRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_trojan_api_ListUsersResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_trojan_api_ListUsersResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_trojan_api_GetUsersRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_trojan_api_GetUsersRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_trojan_api_GetUsersResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_trojan_api_GetUsersResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_trojan_api_SetUsersRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_trojan_api_SetUsersRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_trojan_api_SetUsersResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_trojan_api_SetUsersResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tapi.proto\022\ntrojan.api\";\n\007Traffic\022\026\n\016up" +
      "load_traffic\030\001 \001(\004\022\030\n\020download_traffic\030\002" +
      " \001(\004\"5\n\005Speed\022\024\n\014upload_speed\030\001 \001(\004\022\026\n\016d" +
      "ownload_speed\030\002 \001(\004\"&\n\004User\022\020\n\010password\030" +
      "\001 \001(\t\022\014\n\004hash\030\002 \001(\t\"\320\001\n\nUserStatus\022\036\n\004us" +
      "er\030\001 \001(\0132\020.trojan.api.User\022*\n\rtraffic_to" +
      "tal\030\002 \001(\0132\023.trojan.api.Traffic\022(\n\rspeed_" +
      "current\030\003 \001(\0132\021.trojan.api.Speed\022&\n\013spee" +
      "d_limit\030\004 \001(\0132\021.trojan.api.Speed\022\022\n\nip_c" +
      "urrent\030\005 \001(\005\022\020\n\010ip_limit\030\006 \001(\005\"3\n\021GetTra" +
      "fficRequest\022\036\n\004user\030\001 \001(\0132\020.trojan.api.U" +
      "ser\"\211\001\n\022GetTrafficResponse\022\017\n\007success\030\001 " +
      "\001(\010\022\014\n\004info\030\002 \001(\t\022*\n\rtraffic_total\030\003 \001(\013" +
      "2\023.trojan.api.Traffic\022(\n\rspeed_current\030\004" +
      " \001(\0132\021.trojan.api.Speed\"\022\n\020ListUsersRequ" +
      "est\";\n\021ListUsersResponse\022&\n\006status\030\001 \001(\013" +
      "2\026.trojan.api.UserStatus\"1\n\017GetUsersRequ" +
      "est\022\036\n\004user\030\001 \001(\0132\020.trojan.api.User\"Y\n\020G" +
      "etUsersResponse\022\017\n\007success\030\001 \001(\010\022\014\n\004info" +
      "\030\002 \001(\t\022&\n\006status\030\003 \001(\0132\026.trojan.api.User" +
      "Status\"\241\001\n\017SetUsersRequest\022&\n\006status\030\001 \001" +
      "(\0132\026.trojan.api.UserStatus\0228\n\toperation\030" +
      "\002 \001(\0162%.trojan.api.SetUsersRequest.Opera" +
      "tion\",\n\tOperation\022\007\n\003Add\020\000\022\n\n\006Delete\020\001\022\n" +
      "\n\006Modify\020\002\"1\n\020SetUsersResponse\022\017\n\007succes" +
      "s\030\001 \001(\010\022\014\n\004info\030\002 \001(\t2d\n\023TrojanClientSer" +
      "vice\022M\n\nGetTraffic\022\035.trojan.api.GetTraff" +
      "icRequest\032\036.trojan.api.GetTrafficRespons" +
      "e\"\0002\375\001\n\023TrojanServerService\022L\n\tListUsers" +
      "\022\034.trojan.api.ListUsersRequest\032\035.trojan." +
      "api.ListUsersResponse\"\0000\001\022K\n\010GetUsers\022\033." +
      "trojan.api.GetUsersRequest\032\034.trojan.api." +
      "GetUsersResponse\"\000(\0010\001\022K\n\010SetUsers\022\033.tro" +
      "jan.api.SetUsersRequest\032\034.trojan.api.Set" +
      "UsersResponse\"\000(\0010\001B\'\n\016com.spw.proto2B\020H" +
      "elloWorldProto2P\001\210\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_trojan_api_Traffic_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_trojan_api_Traffic_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_trojan_api_Traffic_descriptor,
        new java.lang.String[] { "UploadTraffic", "DownloadTraffic", });
    internal_static_trojan_api_Speed_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_trojan_api_Speed_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_trojan_api_Speed_descriptor,
        new java.lang.String[] { "UploadSpeed", "DownloadSpeed", });
    internal_static_trojan_api_User_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_trojan_api_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_trojan_api_User_descriptor,
        new java.lang.String[] { "Password", "Hash", });
    internal_static_trojan_api_UserStatus_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_trojan_api_UserStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_trojan_api_UserStatus_descriptor,
        new java.lang.String[] { "User", "TrafficTotal", "SpeedCurrent", "SpeedLimit", "IpCurrent", "IpLimit", });
    internal_static_trojan_api_GetTrafficRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_trojan_api_GetTrafficRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_trojan_api_GetTrafficRequest_descriptor,
        new java.lang.String[] { "User", });
    internal_static_trojan_api_GetTrafficResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_trojan_api_GetTrafficResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_trojan_api_GetTrafficResponse_descriptor,
        new java.lang.String[] { "Success", "Info", "TrafficTotal", "SpeedCurrent", });
    internal_static_trojan_api_ListUsersRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_trojan_api_ListUsersRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_trojan_api_ListUsersRequest_descriptor,
        new java.lang.String[] { });
    internal_static_trojan_api_ListUsersResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_trojan_api_ListUsersResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_trojan_api_ListUsersResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_trojan_api_GetUsersRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_trojan_api_GetUsersRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_trojan_api_GetUsersRequest_descriptor,
        new java.lang.String[] { "User", });
    internal_static_trojan_api_GetUsersResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_trojan_api_GetUsersResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_trojan_api_GetUsersResponse_descriptor,
        new java.lang.String[] { "Success", "Info", "Status", });
    internal_static_trojan_api_SetUsersRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_trojan_api_SetUsersRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_trojan_api_SetUsersRequest_descriptor,
        new java.lang.String[] { "Status", "Operation", });
    internal_static_trojan_api_SetUsersResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_trojan_api_SetUsersResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_trojan_api_SetUsersResponse_descriptor,
        new java.lang.String[] { "Success", "Info", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
