// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package com.spw.proto2;

public interface ListUsersRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:trojan.api.ListUsersRequest)
    com.google.protobuf.MessageOrBuilder {
}
