// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package com.spw.proto2;

public interface SpeedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:trojan.api.Speed)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 upload_speed = 1;</code>
   */
  long getUploadSpeed();

  /**
   * <code>uint64 download_speed = 2;</code>
   */
  long getDownloadSpeed();
}
