// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package com.spw.proto2;

/**
 * Protobuf type {@code trojan.api.Speed}
 */
public  final class Speed extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:trojan.api.Speed)
    SpeedOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Speed.newBuilder() to construct.
  private Speed(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Speed() {
    uploadSpeed_ = 0L;
    downloadSpeed_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Speed(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            uploadSpeed_ = input.readUInt64();
            break;
          }
          case 16: {

            downloadSpeed_ = input.readUInt64();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.spw.proto2.HelloWorldProto2.internal_static_trojan_api_Speed_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.spw.proto2.HelloWorldProto2.internal_static_trojan_api_Speed_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.spw.proto2.Speed.class, com.spw.proto2.Speed.Builder.class);
  }

  public static final int UPLOAD_SPEED_FIELD_NUMBER = 1;
  private long uploadSpeed_;
  /**
   * <code>uint64 upload_speed = 1;</code>
   */
  public long getUploadSpeed() {
    return uploadSpeed_;
  }

  public static final int DOWNLOAD_SPEED_FIELD_NUMBER = 2;
  private long downloadSpeed_;
  /**
   * <code>uint64 download_speed = 2;</code>
   */
  public long getDownloadSpeed() {
    return downloadSpeed_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (uploadSpeed_ != 0L) {
      output.writeUInt64(1, uploadSpeed_);
    }
    if (downloadSpeed_ != 0L) {
      output.writeUInt64(2, downloadSpeed_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (uploadSpeed_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, uploadSpeed_);
    }
    if (downloadSpeed_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(2, downloadSpeed_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.spw.proto2.Speed)) {
      return super.equals(obj);
    }
    com.spw.proto2.Speed other = (com.spw.proto2.Speed) obj;

    boolean result = true;
    result = result && (getUploadSpeed()
        == other.getUploadSpeed());
    result = result && (getDownloadSpeed()
        == other.getDownloadSpeed());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + UPLOAD_SPEED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUploadSpeed());
    hash = (37 * hash) + DOWNLOAD_SPEED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getDownloadSpeed());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.spw.proto2.Speed parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.spw.proto2.Speed parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.spw.proto2.Speed parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.spw.proto2.Speed parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.spw.proto2.Speed parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.spw.proto2.Speed parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.spw.proto2.Speed parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.spw.proto2.Speed parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.spw.proto2.Speed parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.spw.proto2.Speed parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.spw.proto2.Speed parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.spw.proto2.Speed parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.spw.proto2.Speed prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code trojan.api.Speed}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:trojan.api.Speed)
      com.spw.proto2.SpeedOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.spw.proto2.HelloWorldProto2.internal_static_trojan_api_Speed_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.spw.proto2.HelloWorldProto2.internal_static_trojan_api_Speed_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.spw.proto2.Speed.class, com.spw.proto2.Speed.Builder.class);
    }

    // Construct using com.spw.proto2.Speed.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      uploadSpeed_ = 0L;

      downloadSpeed_ = 0L;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.spw.proto2.HelloWorldProto2.internal_static_trojan_api_Speed_descriptor;
    }

    public com.spw.proto2.Speed getDefaultInstanceForType() {
      return com.spw.proto2.Speed.getDefaultInstance();
    }

    public com.spw.proto2.Speed build() {
      com.spw.proto2.Speed result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.spw.proto2.Speed buildPartial() {
      com.spw.proto2.Speed result = new com.spw.proto2.Speed(this);
      result.uploadSpeed_ = uploadSpeed_;
      result.downloadSpeed_ = downloadSpeed_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.spw.proto2.Speed) {
        return mergeFrom((com.spw.proto2.Speed)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.spw.proto2.Speed other) {
      if (other == com.spw.proto2.Speed.getDefaultInstance()) return this;
      if (other.getUploadSpeed() != 0L) {
        setUploadSpeed(other.getUploadSpeed());
      }
      if (other.getDownloadSpeed() != 0L) {
        setDownloadSpeed(other.getDownloadSpeed());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.spw.proto2.Speed parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.spw.proto2.Speed) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long uploadSpeed_ ;
    /**
     * <code>uint64 upload_speed = 1;</code>
     */
    public long getUploadSpeed() {
      return uploadSpeed_;
    }
    /**
     * <code>uint64 upload_speed = 1;</code>
     */
    public Builder setUploadSpeed(long value) {
      
      uploadSpeed_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 upload_speed = 1;</code>
     */
    public Builder clearUploadSpeed() {
      
      uploadSpeed_ = 0L;
      onChanged();
      return this;
    }

    private long downloadSpeed_ ;
    /**
     * <code>uint64 download_speed = 2;</code>
     */
    public long getDownloadSpeed() {
      return downloadSpeed_;
    }
    /**
     * <code>uint64 download_speed = 2;</code>
     */
    public Builder setDownloadSpeed(long value) {
      
      downloadSpeed_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 download_speed = 2;</code>
     */
    public Builder clearDownloadSpeed() {
      
      downloadSpeed_ = 0L;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:trojan.api.Speed)
  }

  // @@protoc_insertion_point(class_scope:trojan.api.Speed)
  private static final com.spw.proto2.Speed DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.spw.proto2.Speed();
  }

  public static com.spw.proto2.Speed getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Speed>
      PARSER = new com.google.protobuf.AbstractParser<Speed>() {
    public Speed parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Speed(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Speed> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Speed> getParserForType() {
    return PARSER;
  }

  public com.spw.proto2.Speed getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

