// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package com.spw.proto2;

public interface TrafficOrBuilder extends
    // @@protoc_insertion_point(interface_extends:trojan.api.Traffic)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 upload_traffic = 1;</code>
   */
  long getUploadTraffic();

  /**
   * <code>uint64 download_traffic = 2;</code>
   */
  long getDownloadTraffic();
}
