// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package com.spw.proto2;

/**
 * Protobuf service {@code trojan.api.TrojanServerService}
 */
public  abstract class TrojanServerService
    implements com.google.protobuf.Service {
  protected TrojanServerService() {}

  public interface Interface {
    /**
     * <pre>
     * list all users
     * </pre>
     *
     * <code>rpc ListUsers(.trojan.api.ListUsersRequest) returns (stream .trojan.api.ListUsersResponse);</code>
     */
    public abstract void listUsers(
        com.google.protobuf.RpcController controller,
        com.spw.proto2.ListUsersRequest request,
        com.google.protobuf.RpcCallback<com.spw.proto2.ListUsersResponse> done);

    /**
     * <pre>
     * obtain specified user's info
     * </pre>
     *
     * <code>rpc GetUsers(stream .trojan.api.GetUsersRequest) returns (stream .trojan.api.GetUsersResponse);</code>
     */
    public abstract void getUsers(
        com.google.protobuf.RpcController controller,
        com.spw.proto2.GetUsersRequest request,
        com.google.protobuf.RpcCallback<com.spw.proto2.GetUsersResponse> done);

    /**
     * <pre>
     * setup existing users' config
     * </pre>
     *
     * <code>rpc SetUsers(stream .trojan.api.SetUsersRequest) returns (stream .trojan.api.SetUsersResponse);</code>
     */
    public abstract void setUsers(
        com.google.protobuf.RpcController controller,
        com.spw.proto2.SetUsersRequest request,
        com.google.protobuf.RpcCallback<com.spw.proto2.SetUsersResponse> done);

  }

  public static com.google.protobuf.Service newReflectiveService(
      final Interface impl) {
    return new TrojanServerService() {
      @java.lang.Override
      public  void listUsers(
          com.google.protobuf.RpcController controller,
          com.spw.proto2.ListUsersRequest request,
          com.google.protobuf.RpcCallback<com.spw.proto2.ListUsersResponse> done) {
        impl.listUsers(controller, request, done);
      }

      @java.lang.Override
      public  void getUsers(
          com.google.protobuf.RpcController controller,
          com.spw.proto2.GetUsersRequest request,
          com.google.protobuf.RpcCallback<com.spw.proto2.GetUsersResponse> done) {
        impl.getUsers(controller, request, done);
      }

      @java.lang.Override
      public  void setUsers(
          com.google.protobuf.RpcController controller,
          com.spw.proto2.SetUsersRequest request,
          com.google.protobuf.RpcCallback<com.spw.proto2.SetUsersResponse> done) {
        impl.setUsers(controller, request, done);
      }

    };
  }

  public static com.google.protobuf.BlockingService
      newReflectiveBlockingService(final BlockingInterface impl) {
    return new com.google.protobuf.BlockingService() {
      public final com.google.protobuf.Descriptors.ServiceDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }

      public final com.google.protobuf.Message callBlockingMethod(
          com.google.protobuf.Descriptors.MethodDescriptor method,
          com.google.protobuf.RpcController controller,
          com.google.protobuf.Message request)
          throws com.google.protobuf.ServiceException {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.callBlockingMethod() given method descriptor for " +
            "wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return impl.listUsers(controller, (com.spw.proto2.ListUsersRequest)request);
          case 1:
            return impl.getUsers(controller, (com.spw.proto2.GetUsersRequest)request);
          case 2:
            return impl.setUsers(controller, (com.spw.proto2.SetUsersRequest)request);
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getRequestPrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getRequestPrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return com.spw.proto2.ListUsersRequest.getDefaultInstance();
          case 1:
            return com.spw.proto2.GetUsersRequest.getDefaultInstance();
          case 2:
            return com.spw.proto2.SetUsersRequest.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getResponsePrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getResponsePrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return com.spw.proto2.ListUsersResponse.getDefaultInstance();
          case 1:
            return com.spw.proto2.GetUsersResponse.getDefaultInstance();
          case 2:
            return com.spw.proto2.SetUsersResponse.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

    };
  }

  /**
   * <pre>
   * list all users
   * </pre>
   *
   * <code>rpc ListUsers(.trojan.api.ListUsersRequest) returns (stream .trojan.api.ListUsersResponse);</code>
   */
  public abstract void listUsers(
      com.google.protobuf.RpcController controller,
      com.spw.proto2.ListUsersRequest request,
      com.google.protobuf.RpcCallback<com.spw.proto2.ListUsersResponse> done);

  /**
   * <pre>
   * obtain specified user's info
   * </pre>
   *
   * <code>rpc GetUsers(stream .trojan.api.GetUsersRequest) returns (stream .trojan.api.GetUsersResponse);</code>
   */
  public abstract void getUsers(
      com.google.protobuf.RpcController controller,
      com.spw.proto2.GetUsersRequest request,
      com.google.protobuf.RpcCallback<com.spw.proto2.GetUsersResponse> done);

  /**
   * <pre>
   * setup existing users' config
   * </pre>
   *
   * <code>rpc SetUsers(stream .trojan.api.SetUsersRequest) returns (stream .trojan.api.SetUsersResponse);</code>
   */
  public abstract void setUsers(
      com.google.protobuf.RpcController controller,
      com.spw.proto2.SetUsersRequest request,
      com.google.protobuf.RpcCallback<com.spw.proto2.SetUsersResponse> done);

  public static final
      com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptor() {
    return com.spw.proto2.HelloWorldProto2.getDescriptor().getServices().get(1);
  }
  public final com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }

  public final void callMethod(
      com.google.protobuf.Descriptors.MethodDescriptor method,
      com.google.protobuf.RpcController controller,
      com.google.protobuf.Message request,
      com.google.protobuf.RpcCallback<
        com.google.protobuf.Message> done) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.callMethod() given method descriptor for wrong " +
        "service type.");
    }
    switch(method.getIndex()) {
      case 0:
        this.listUsers(controller, (com.spw.proto2.ListUsersRequest)request,
          com.google.protobuf.RpcUtil.<com.spw.proto2.ListUsersResponse>specializeCallback(
            done));
        return;
      case 1:
        this.getUsers(controller, (com.spw.proto2.GetUsersRequest)request,
          com.google.protobuf.RpcUtil.<com.spw.proto2.GetUsersResponse>specializeCallback(
            done));
        return;
      case 2:
        this.setUsers(controller, (com.spw.proto2.SetUsersRequest)request,
          com.google.protobuf.RpcUtil.<com.spw.proto2.SetUsersResponse>specializeCallback(
            done));
        return;
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getRequestPrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getRequestPrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return com.spw.proto2.ListUsersRequest.getDefaultInstance();
      case 1:
        return com.spw.proto2.GetUsersRequest.getDefaultInstance();
      case 2:
        return com.spw.proto2.SetUsersRequest.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getResponsePrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getResponsePrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return com.spw.proto2.ListUsersResponse.getDefaultInstance();
      case 1:
        return com.spw.proto2.GetUsersResponse.getDefaultInstance();
      case 2:
        return com.spw.proto2.SetUsersResponse.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public static Stub newStub(
      com.google.protobuf.RpcChannel channel) {
    return new Stub(channel);
  }

  public static final class Stub extends com.spw.proto2.TrojanServerService implements Interface {
    private Stub(com.google.protobuf.RpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.RpcChannel channel;

    public com.google.protobuf.RpcChannel getChannel() {
      return channel;
    }

    public  void listUsers(
        com.google.protobuf.RpcController controller,
        com.spw.proto2.ListUsersRequest request,
        com.google.protobuf.RpcCallback<com.spw.proto2.ListUsersResponse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        com.spw.proto2.ListUsersResponse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          com.spw.proto2.ListUsersResponse.class,
          com.spw.proto2.ListUsersResponse.getDefaultInstance()));
    }

    public  void getUsers(
        com.google.protobuf.RpcController controller,
        com.spw.proto2.GetUsersRequest request,
        com.google.protobuf.RpcCallback<com.spw.proto2.GetUsersResponse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(1),
        controller,
        request,
        com.spw.proto2.GetUsersResponse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          com.spw.proto2.GetUsersResponse.class,
          com.spw.proto2.GetUsersResponse.getDefaultInstance()));
    }

    public  void setUsers(
        com.google.protobuf.RpcController controller,
        com.spw.proto2.SetUsersRequest request,
        com.google.protobuf.RpcCallback<com.spw.proto2.SetUsersResponse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(2),
        controller,
        request,
        com.spw.proto2.SetUsersResponse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          com.spw.proto2.SetUsersResponse.class,
          com.spw.proto2.SetUsersResponse.getDefaultInstance()));
    }
  }

  public static BlockingInterface newBlockingStub(
      com.google.protobuf.BlockingRpcChannel channel) {
    return new BlockingStub(channel);
  }

  public interface BlockingInterface {
    public com.spw.proto2.ListUsersResponse listUsers(
        com.google.protobuf.RpcController controller,
        com.spw.proto2.ListUsersRequest request)
        throws com.google.protobuf.ServiceException;

    public com.spw.proto2.GetUsersResponse getUsers(
        com.google.protobuf.RpcController controller,
        com.spw.proto2.GetUsersRequest request)
        throws com.google.protobuf.ServiceException;

    public com.spw.proto2.SetUsersResponse setUsers(
        com.google.protobuf.RpcController controller,
        com.spw.proto2.SetUsersRequest request)
        throws com.google.protobuf.ServiceException;
  }

  private static final class BlockingStub implements BlockingInterface {
    private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.BlockingRpcChannel channel;

    public com.spw.proto2.ListUsersResponse listUsers(
        com.google.protobuf.RpcController controller,
        com.spw.proto2.ListUsersRequest request)
        throws com.google.protobuf.ServiceException {
      return (com.spw.proto2.ListUsersResponse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        com.spw.proto2.ListUsersResponse.getDefaultInstance());
    }


    public com.spw.proto2.GetUsersResponse getUsers(
        com.google.protobuf.RpcController controller,
        com.spw.proto2.GetUsersRequest request)
        throws com.google.protobuf.ServiceException {
      return (com.spw.proto2.GetUsersResponse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(1),
        controller,
        request,
        com.spw.proto2.GetUsersResponse.getDefaultInstance());
    }


    public com.spw.proto2.SetUsersResponse setUsers(
        com.google.protobuf.RpcController controller,
        com.spw.proto2.SetUsersRequest request)
        throws com.google.protobuf.ServiceException {
      return (com.spw.proto2.SetUsersResponse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(2),
        controller,
        request,
        com.spw.proto2.SetUsersResponse.getDefaultInstance());
    }

  }

  // @@protoc_insertion_point(class_scope:trojan.api.TrojanServerService)
}

