// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package com.spw.proto2;

/**
 * Protobuf type {@code trojan.api.UserStatus}
 */
public  final class UserStatus extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:trojan.api.UserStatus)
    UserStatusOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UserStatus.newBuilder() to construct.
  private UserStatus(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UserStatus() {
    ipCurrent_ = 0;
    ipLimit_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private UserStatus(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.spw.proto2.User.Builder subBuilder = null;
            if (user_ != null) {
              subBuilder = user_.toBuilder();
            }
            user_ = input.readMessage(com.spw.proto2.User.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(user_);
              user_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.spw.proto2.Traffic.Builder subBuilder = null;
            if (trafficTotal_ != null) {
              subBuilder = trafficTotal_.toBuilder();
            }
            trafficTotal_ = input.readMessage(com.spw.proto2.Traffic.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(trafficTotal_);
              trafficTotal_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            com.spw.proto2.Speed.Builder subBuilder = null;
            if (speedCurrent_ != null) {
              subBuilder = speedCurrent_.toBuilder();
            }
            speedCurrent_ = input.readMessage(com.spw.proto2.Speed.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(speedCurrent_);
              speedCurrent_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            com.spw.proto2.Speed.Builder subBuilder = null;
            if (speedLimit_ != null) {
              subBuilder = speedLimit_.toBuilder();
            }
            speedLimit_ = input.readMessage(com.spw.proto2.Speed.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(speedLimit_);
              speedLimit_ = subBuilder.buildPartial();
            }

            break;
          }
          case 40: {

            ipCurrent_ = input.readInt32();
            break;
          }
          case 48: {

            ipLimit_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.spw.proto2.HelloWorldProto2.internal_static_trojan_api_UserStatus_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.spw.proto2.HelloWorldProto2.internal_static_trojan_api_UserStatus_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.spw.proto2.UserStatus.class, com.spw.proto2.UserStatus.Builder.class);
  }

  public static final int USER_FIELD_NUMBER = 1;
  private com.spw.proto2.User user_;
  /**
   * <code>.trojan.api.User user = 1;</code>
   */
  public boolean hasUser() {
    return user_ != null;
  }
  /**
   * <code>.trojan.api.User user = 1;</code>
   */
  public com.spw.proto2.User getUser() {
    return user_ == null ? com.spw.proto2.User.getDefaultInstance() : user_;
  }
  /**
   * <code>.trojan.api.User user = 1;</code>
   */
  public com.spw.proto2.UserOrBuilder getUserOrBuilder() {
    return getUser();
  }

  public static final int TRAFFIC_TOTAL_FIELD_NUMBER = 2;
  private com.spw.proto2.Traffic trafficTotal_;
  /**
   * <code>.trojan.api.Traffic traffic_total = 2;</code>
   */
  public boolean hasTrafficTotal() {
    return trafficTotal_ != null;
  }
  /**
   * <code>.trojan.api.Traffic traffic_total = 2;</code>
   */
  public com.spw.proto2.Traffic getTrafficTotal() {
    return trafficTotal_ == null ? com.spw.proto2.Traffic.getDefaultInstance() : trafficTotal_;
  }
  /**
   * <code>.trojan.api.Traffic traffic_total = 2;</code>
   */
  public com.spw.proto2.TrafficOrBuilder getTrafficTotalOrBuilder() {
    return getTrafficTotal();
  }

  public static final int SPEED_CURRENT_FIELD_NUMBER = 3;
  private com.spw.proto2.Speed speedCurrent_;
  /**
   * <code>.trojan.api.Speed speed_current = 3;</code>
   */
  public boolean hasSpeedCurrent() {
    return speedCurrent_ != null;
  }
  /**
   * <code>.trojan.api.Speed speed_current = 3;</code>
   */
  public com.spw.proto2.Speed getSpeedCurrent() {
    return speedCurrent_ == null ? com.spw.proto2.Speed.getDefaultInstance() : speedCurrent_;
  }
  /**
   * <code>.trojan.api.Speed speed_current = 3;</code>
   */
  public com.spw.proto2.SpeedOrBuilder getSpeedCurrentOrBuilder() {
    return getSpeedCurrent();
  }

  public static final int SPEED_LIMIT_FIELD_NUMBER = 4;
  private com.spw.proto2.Speed speedLimit_;
  /**
   * <code>.trojan.api.Speed speed_limit = 4;</code>
   */
  public boolean hasSpeedLimit() {
    return speedLimit_ != null;
  }
  /**
   * <code>.trojan.api.Speed speed_limit = 4;</code>
   */
  public com.spw.proto2.Speed getSpeedLimit() {
    return speedLimit_ == null ? com.spw.proto2.Speed.getDefaultInstance() : speedLimit_;
  }
  /**
   * <code>.trojan.api.Speed speed_limit = 4;</code>
   */
  public com.spw.proto2.SpeedOrBuilder getSpeedLimitOrBuilder() {
    return getSpeedLimit();
  }

  public static final int IP_CURRENT_FIELD_NUMBER = 5;
  private int ipCurrent_;
  /**
   * <code>int32 ip_current = 5;</code>
   */
  public int getIpCurrent() {
    return ipCurrent_;
  }

  public static final int IP_LIMIT_FIELD_NUMBER = 6;
  private int ipLimit_;
  /**
   * <code>int32 ip_limit = 6;</code>
   */
  public int getIpLimit() {
    return ipLimit_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (user_ != null) {
      output.writeMessage(1, getUser());
    }
    if (trafficTotal_ != null) {
      output.writeMessage(2, getTrafficTotal());
    }
    if (speedCurrent_ != null) {
      output.writeMessage(3, getSpeedCurrent());
    }
    if (speedLimit_ != null) {
      output.writeMessage(4, getSpeedLimit());
    }
    if (ipCurrent_ != 0) {
      output.writeInt32(5, ipCurrent_);
    }
    if (ipLimit_ != 0) {
      output.writeInt32(6, ipLimit_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (user_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getUser());
    }
    if (trafficTotal_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getTrafficTotal());
    }
    if (speedCurrent_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getSpeedCurrent());
    }
    if (speedLimit_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getSpeedLimit());
    }
    if (ipCurrent_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, ipCurrent_);
    }
    if (ipLimit_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, ipLimit_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.spw.proto2.UserStatus)) {
      return super.equals(obj);
    }
    com.spw.proto2.UserStatus other = (com.spw.proto2.UserStatus) obj;

    boolean result = true;
    result = result && (hasUser() == other.hasUser());
    if (hasUser()) {
      result = result && getUser()
          .equals(other.getUser());
    }
    result = result && (hasTrafficTotal() == other.hasTrafficTotal());
    if (hasTrafficTotal()) {
      result = result && getTrafficTotal()
          .equals(other.getTrafficTotal());
    }
    result = result && (hasSpeedCurrent() == other.hasSpeedCurrent());
    if (hasSpeedCurrent()) {
      result = result && getSpeedCurrent()
          .equals(other.getSpeedCurrent());
    }
    result = result && (hasSpeedLimit() == other.hasSpeedLimit());
    if (hasSpeedLimit()) {
      result = result && getSpeedLimit()
          .equals(other.getSpeedLimit());
    }
    result = result && (getIpCurrent()
        == other.getIpCurrent());
    result = result && (getIpLimit()
        == other.getIpLimit());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasUser()) {
      hash = (37 * hash) + USER_FIELD_NUMBER;
      hash = (53 * hash) + getUser().hashCode();
    }
    if (hasTrafficTotal()) {
      hash = (37 * hash) + TRAFFIC_TOTAL_FIELD_NUMBER;
      hash = (53 * hash) + getTrafficTotal().hashCode();
    }
    if (hasSpeedCurrent()) {
      hash = (37 * hash) + SPEED_CURRENT_FIELD_NUMBER;
      hash = (53 * hash) + getSpeedCurrent().hashCode();
    }
    if (hasSpeedLimit()) {
      hash = (37 * hash) + SPEED_LIMIT_FIELD_NUMBER;
      hash = (53 * hash) + getSpeedLimit().hashCode();
    }
    hash = (37 * hash) + IP_CURRENT_FIELD_NUMBER;
    hash = (53 * hash) + getIpCurrent();
    hash = (37 * hash) + IP_LIMIT_FIELD_NUMBER;
    hash = (53 * hash) + getIpLimit();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.spw.proto2.UserStatus parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.spw.proto2.UserStatus parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.spw.proto2.UserStatus parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.spw.proto2.UserStatus parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.spw.proto2.UserStatus parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.spw.proto2.UserStatus parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.spw.proto2.UserStatus parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.spw.proto2.UserStatus parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.spw.proto2.UserStatus parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.spw.proto2.UserStatus parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.spw.proto2.UserStatus parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.spw.proto2.UserStatus parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.spw.proto2.UserStatus prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code trojan.api.UserStatus}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:trojan.api.UserStatus)
      com.spw.proto2.UserStatusOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.spw.proto2.HelloWorldProto2.internal_static_trojan_api_UserStatus_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.spw.proto2.HelloWorldProto2.internal_static_trojan_api_UserStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.spw.proto2.UserStatus.class, com.spw.proto2.UserStatus.Builder.class);
    }

    // Construct using com.spw.proto2.UserStatus.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (userBuilder_ == null) {
        user_ = null;
      } else {
        user_ = null;
        userBuilder_ = null;
      }
      if (trafficTotalBuilder_ == null) {
        trafficTotal_ = null;
      } else {
        trafficTotal_ = null;
        trafficTotalBuilder_ = null;
      }
      if (speedCurrentBuilder_ == null) {
        speedCurrent_ = null;
      } else {
        speedCurrent_ = null;
        speedCurrentBuilder_ = null;
      }
      if (speedLimitBuilder_ == null) {
        speedLimit_ = null;
      } else {
        speedLimit_ = null;
        speedLimitBuilder_ = null;
      }
      ipCurrent_ = 0;

      ipLimit_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.spw.proto2.HelloWorldProto2.internal_static_trojan_api_UserStatus_descriptor;
    }

    public com.spw.proto2.UserStatus getDefaultInstanceForType() {
      return com.spw.proto2.UserStatus.getDefaultInstance();
    }

    public com.spw.proto2.UserStatus build() {
      com.spw.proto2.UserStatus result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.spw.proto2.UserStatus buildPartial() {
      com.spw.proto2.UserStatus result = new com.spw.proto2.UserStatus(this);
      if (userBuilder_ == null) {
        result.user_ = user_;
      } else {
        result.user_ = userBuilder_.build();
      }
      if (trafficTotalBuilder_ == null) {
        result.trafficTotal_ = trafficTotal_;
      } else {
        result.trafficTotal_ = trafficTotalBuilder_.build();
      }
      if (speedCurrentBuilder_ == null) {
        result.speedCurrent_ = speedCurrent_;
      } else {
        result.speedCurrent_ = speedCurrentBuilder_.build();
      }
      if (speedLimitBuilder_ == null) {
        result.speedLimit_ = speedLimit_;
      } else {
        result.speedLimit_ = speedLimitBuilder_.build();
      }
      result.ipCurrent_ = ipCurrent_;
      result.ipLimit_ = ipLimit_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.spw.proto2.UserStatus) {
        return mergeFrom((com.spw.proto2.UserStatus)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.spw.proto2.UserStatus other) {
      if (other == com.spw.proto2.UserStatus.getDefaultInstance()) return this;
      if (other.hasUser()) {
        mergeUser(other.getUser());
      }
      if (other.hasTrafficTotal()) {
        mergeTrafficTotal(other.getTrafficTotal());
      }
      if (other.hasSpeedCurrent()) {
        mergeSpeedCurrent(other.getSpeedCurrent());
      }
      if (other.hasSpeedLimit()) {
        mergeSpeedLimit(other.getSpeedLimit());
      }
      if (other.getIpCurrent() != 0) {
        setIpCurrent(other.getIpCurrent());
      }
      if (other.getIpLimit() != 0) {
        setIpLimit(other.getIpLimit());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.spw.proto2.UserStatus parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.spw.proto2.UserStatus) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.spw.proto2.User user_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.spw.proto2.User, com.spw.proto2.User.Builder, com.spw.proto2.UserOrBuilder> userBuilder_;
    /**
     * <code>.trojan.api.User user = 1;</code>
     */
    public boolean hasUser() {
      return userBuilder_ != null || user_ != null;
    }
    /**
     * <code>.trojan.api.User user = 1;</code>
     */
    public com.spw.proto2.User getUser() {
      if (userBuilder_ == null) {
        return user_ == null ? com.spw.proto2.User.getDefaultInstance() : user_;
      } else {
        return userBuilder_.getMessage();
      }
    }
    /**
     * <code>.trojan.api.User user = 1;</code>
     */
    public Builder setUser(com.spw.proto2.User value) {
      if (userBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        user_ = value;
        onChanged();
      } else {
        userBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.trojan.api.User user = 1;</code>
     */
    public Builder setUser(
        com.spw.proto2.User.Builder builderForValue) {
      if (userBuilder_ == null) {
        user_ = builderForValue.build();
        onChanged();
      } else {
        userBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.trojan.api.User user = 1;</code>
     */
    public Builder mergeUser(com.spw.proto2.User value) {
      if (userBuilder_ == null) {
        if (user_ != null) {
          user_ =
            com.spw.proto2.User.newBuilder(user_).mergeFrom(value).buildPartial();
        } else {
          user_ = value;
        }
        onChanged();
      } else {
        userBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.trojan.api.User user = 1;</code>
     */
    public Builder clearUser() {
      if (userBuilder_ == null) {
        user_ = null;
        onChanged();
      } else {
        user_ = null;
        userBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.trojan.api.User user = 1;</code>
     */
    public com.spw.proto2.User.Builder getUserBuilder() {
      
      onChanged();
      return getUserFieldBuilder().getBuilder();
    }
    /**
     * <code>.trojan.api.User user = 1;</code>
     */
    public com.spw.proto2.UserOrBuilder getUserOrBuilder() {
      if (userBuilder_ != null) {
        return userBuilder_.getMessageOrBuilder();
      } else {
        return user_ == null ?
            com.spw.proto2.User.getDefaultInstance() : user_;
      }
    }
    /**
     * <code>.trojan.api.User user = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.spw.proto2.User, com.spw.proto2.User.Builder, com.spw.proto2.UserOrBuilder> 
        getUserFieldBuilder() {
      if (userBuilder_ == null) {
        userBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.spw.proto2.User, com.spw.proto2.User.Builder, com.spw.proto2.UserOrBuilder>(
                getUser(),
                getParentForChildren(),
                isClean());
        user_ = null;
      }
      return userBuilder_;
    }

    private com.spw.proto2.Traffic trafficTotal_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.spw.proto2.Traffic, com.spw.proto2.Traffic.Builder, com.spw.proto2.TrafficOrBuilder> trafficTotalBuilder_;
    /**
     * <code>.trojan.api.Traffic traffic_total = 2;</code>
     */
    public boolean hasTrafficTotal() {
      return trafficTotalBuilder_ != null || trafficTotal_ != null;
    }
    /**
     * <code>.trojan.api.Traffic traffic_total = 2;</code>
     */
    public com.spw.proto2.Traffic getTrafficTotal() {
      if (trafficTotalBuilder_ == null) {
        return trafficTotal_ == null ? com.spw.proto2.Traffic.getDefaultInstance() : trafficTotal_;
      } else {
        return trafficTotalBuilder_.getMessage();
      }
    }
    /**
     * <code>.trojan.api.Traffic traffic_total = 2;</code>
     */
    public Builder setTrafficTotal(com.spw.proto2.Traffic value) {
      if (trafficTotalBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        trafficTotal_ = value;
        onChanged();
      } else {
        trafficTotalBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.trojan.api.Traffic traffic_total = 2;</code>
     */
    public Builder setTrafficTotal(
        com.spw.proto2.Traffic.Builder builderForValue) {
      if (trafficTotalBuilder_ == null) {
        trafficTotal_ = builderForValue.build();
        onChanged();
      } else {
        trafficTotalBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.trojan.api.Traffic traffic_total = 2;</code>
     */
    public Builder mergeTrafficTotal(com.spw.proto2.Traffic value) {
      if (trafficTotalBuilder_ == null) {
        if (trafficTotal_ != null) {
          trafficTotal_ =
            com.spw.proto2.Traffic.newBuilder(trafficTotal_).mergeFrom(value).buildPartial();
        } else {
          trafficTotal_ = value;
        }
        onChanged();
      } else {
        trafficTotalBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.trojan.api.Traffic traffic_total = 2;</code>
     */
    public Builder clearTrafficTotal() {
      if (trafficTotalBuilder_ == null) {
        trafficTotal_ = null;
        onChanged();
      } else {
        trafficTotal_ = null;
        trafficTotalBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.trojan.api.Traffic traffic_total = 2;</code>
     */
    public com.spw.proto2.Traffic.Builder getTrafficTotalBuilder() {
      
      onChanged();
      return getTrafficTotalFieldBuilder().getBuilder();
    }
    /**
     * <code>.trojan.api.Traffic traffic_total = 2;</code>
     */
    public com.spw.proto2.TrafficOrBuilder getTrafficTotalOrBuilder() {
      if (trafficTotalBuilder_ != null) {
        return trafficTotalBuilder_.getMessageOrBuilder();
      } else {
        return trafficTotal_ == null ?
            com.spw.proto2.Traffic.getDefaultInstance() : trafficTotal_;
      }
    }
    /**
     * <code>.trojan.api.Traffic traffic_total = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.spw.proto2.Traffic, com.spw.proto2.Traffic.Builder, com.spw.proto2.TrafficOrBuilder> 
        getTrafficTotalFieldBuilder() {
      if (trafficTotalBuilder_ == null) {
        trafficTotalBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.spw.proto2.Traffic, com.spw.proto2.Traffic.Builder, com.spw.proto2.TrafficOrBuilder>(
                getTrafficTotal(),
                getParentForChildren(),
                isClean());
        trafficTotal_ = null;
      }
      return trafficTotalBuilder_;
    }

    private com.spw.proto2.Speed speedCurrent_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.spw.proto2.Speed, com.spw.proto2.Speed.Builder, com.spw.proto2.SpeedOrBuilder> speedCurrentBuilder_;
    /**
     * <code>.trojan.api.Speed speed_current = 3;</code>
     */
    public boolean hasSpeedCurrent() {
      return speedCurrentBuilder_ != null || speedCurrent_ != null;
    }
    /**
     * <code>.trojan.api.Speed speed_current = 3;</code>
     */
    public com.spw.proto2.Speed getSpeedCurrent() {
      if (speedCurrentBuilder_ == null) {
        return speedCurrent_ == null ? com.spw.proto2.Speed.getDefaultInstance() : speedCurrent_;
      } else {
        return speedCurrentBuilder_.getMessage();
      }
    }
    /**
     * <code>.trojan.api.Speed speed_current = 3;</code>
     */
    public Builder setSpeedCurrent(com.spw.proto2.Speed value) {
      if (speedCurrentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        speedCurrent_ = value;
        onChanged();
      } else {
        speedCurrentBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.trojan.api.Speed speed_current = 3;</code>
     */
    public Builder setSpeedCurrent(
        com.spw.proto2.Speed.Builder builderForValue) {
      if (speedCurrentBuilder_ == null) {
        speedCurrent_ = builderForValue.build();
        onChanged();
      } else {
        speedCurrentBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.trojan.api.Speed speed_current = 3;</code>
     */
    public Builder mergeSpeedCurrent(com.spw.proto2.Speed value) {
      if (speedCurrentBuilder_ == null) {
        if (speedCurrent_ != null) {
          speedCurrent_ =
            com.spw.proto2.Speed.newBuilder(speedCurrent_).mergeFrom(value).buildPartial();
        } else {
          speedCurrent_ = value;
        }
        onChanged();
      } else {
        speedCurrentBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.trojan.api.Speed speed_current = 3;</code>
     */
    public Builder clearSpeedCurrent() {
      if (speedCurrentBuilder_ == null) {
        speedCurrent_ = null;
        onChanged();
      } else {
        speedCurrent_ = null;
        speedCurrentBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.trojan.api.Speed speed_current = 3;</code>
     */
    public com.spw.proto2.Speed.Builder getSpeedCurrentBuilder() {
      
      onChanged();
      return getSpeedCurrentFieldBuilder().getBuilder();
    }
    /**
     * <code>.trojan.api.Speed speed_current = 3;</code>
     */
    public com.spw.proto2.SpeedOrBuilder getSpeedCurrentOrBuilder() {
      if (speedCurrentBuilder_ != null) {
        return speedCurrentBuilder_.getMessageOrBuilder();
      } else {
        return speedCurrent_ == null ?
            com.spw.proto2.Speed.getDefaultInstance() : speedCurrent_;
      }
    }
    /**
     * <code>.trojan.api.Speed speed_current = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.spw.proto2.Speed, com.spw.proto2.Speed.Builder, com.spw.proto2.SpeedOrBuilder> 
        getSpeedCurrentFieldBuilder() {
      if (speedCurrentBuilder_ == null) {
        speedCurrentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.spw.proto2.Speed, com.spw.proto2.Speed.Builder, com.spw.proto2.SpeedOrBuilder>(
                getSpeedCurrent(),
                getParentForChildren(),
                isClean());
        speedCurrent_ = null;
      }
      return speedCurrentBuilder_;
    }

    private com.spw.proto2.Speed speedLimit_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.spw.proto2.Speed, com.spw.proto2.Speed.Builder, com.spw.proto2.SpeedOrBuilder> speedLimitBuilder_;
    /**
     * <code>.trojan.api.Speed speed_limit = 4;</code>
     */
    public boolean hasSpeedLimit() {
      return speedLimitBuilder_ != null || speedLimit_ != null;
    }
    /**
     * <code>.trojan.api.Speed speed_limit = 4;</code>
     */
    public com.spw.proto2.Speed getSpeedLimit() {
      if (speedLimitBuilder_ == null) {
        return speedLimit_ == null ? com.spw.proto2.Speed.getDefaultInstance() : speedLimit_;
      } else {
        return speedLimitBuilder_.getMessage();
      }
    }
    /**
     * <code>.trojan.api.Speed speed_limit = 4;</code>
     */
    public Builder setSpeedLimit(com.spw.proto2.Speed value) {
      if (speedLimitBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        speedLimit_ = value;
        onChanged();
      } else {
        speedLimitBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.trojan.api.Speed speed_limit = 4;</code>
     */
    public Builder setSpeedLimit(
        com.spw.proto2.Speed.Builder builderForValue) {
      if (speedLimitBuilder_ == null) {
        speedLimit_ = builderForValue.build();
        onChanged();
      } else {
        speedLimitBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.trojan.api.Speed speed_limit = 4;</code>
     */
    public Builder mergeSpeedLimit(com.spw.proto2.Speed value) {
      if (speedLimitBuilder_ == null) {
        if (speedLimit_ != null) {
          speedLimit_ =
            com.spw.proto2.Speed.newBuilder(speedLimit_).mergeFrom(value).buildPartial();
        } else {
          speedLimit_ = value;
        }
        onChanged();
      } else {
        speedLimitBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.trojan.api.Speed speed_limit = 4;</code>
     */
    public Builder clearSpeedLimit() {
      if (speedLimitBuilder_ == null) {
        speedLimit_ = null;
        onChanged();
      } else {
        speedLimit_ = null;
        speedLimitBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.trojan.api.Speed speed_limit = 4;</code>
     */
    public com.spw.proto2.Speed.Builder getSpeedLimitBuilder() {
      
      onChanged();
      return getSpeedLimitFieldBuilder().getBuilder();
    }
    /**
     * <code>.trojan.api.Speed speed_limit = 4;</code>
     */
    public com.spw.proto2.SpeedOrBuilder getSpeedLimitOrBuilder() {
      if (speedLimitBuilder_ != null) {
        return speedLimitBuilder_.getMessageOrBuilder();
      } else {
        return speedLimit_ == null ?
            com.spw.proto2.Speed.getDefaultInstance() : speedLimit_;
      }
    }
    /**
     * <code>.trojan.api.Speed speed_limit = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.spw.proto2.Speed, com.spw.proto2.Speed.Builder, com.spw.proto2.SpeedOrBuilder> 
        getSpeedLimitFieldBuilder() {
      if (speedLimitBuilder_ == null) {
        speedLimitBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.spw.proto2.Speed, com.spw.proto2.Speed.Builder, com.spw.proto2.SpeedOrBuilder>(
                getSpeedLimit(),
                getParentForChildren(),
                isClean());
        speedLimit_ = null;
      }
      return speedLimitBuilder_;
    }

    private int ipCurrent_ ;
    /**
     * <code>int32 ip_current = 5;</code>
     */
    public int getIpCurrent() {
      return ipCurrent_;
    }
    /**
     * <code>int32 ip_current = 5;</code>
     */
    public Builder setIpCurrent(int value) {
      
      ipCurrent_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 ip_current = 5;</code>
     */
    public Builder clearIpCurrent() {
      
      ipCurrent_ = 0;
      onChanged();
      return this;
    }

    private int ipLimit_ ;
    /**
     * <code>int32 ip_limit = 6;</code>
     */
    public int getIpLimit() {
      return ipLimit_;
    }
    /**
     * <code>int32 ip_limit = 6;</code>
     */
    public Builder setIpLimit(int value) {
      
      ipLimit_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 ip_limit = 6;</code>
     */
    public Builder clearIpLimit() {
      
      ipLimit_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:trojan.api.UserStatus)
  }

  // @@protoc_insertion_point(class_scope:trojan.api.UserStatus)
  private static final com.spw.proto2.UserStatus DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.spw.proto2.UserStatus();
  }

  public static com.spw.proto2.UserStatus getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UserStatus>
      PARSER = new com.google.protobuf.AbstractParser<UserStatus>() {
    public UserStatus parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UserStatus(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UserStatus> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UserStatus> getParserForType() {
    return PARSER;
  }

  public com.spw.proto2.UserStatus getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

