// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package com.spw.proto2;

public interface UserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:trojan.api.User)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string password = 1;</code>
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 1;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>string hash = 2;</code>
   */
  java.lang.String getHash();
  /**
   * <code>string hash = 2;</code>
   */
  com.google.protobuf.ByteString
      getHashBytes();
}
