// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package com.spw.proto2;

public interface UserStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:trojan.api.UserStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.trojan.api.User user = 1;</code>
   */
  boolean hasUser();
  /**
   * <code>.trojan.api.User user = 1;</code>
   */
  com.spw.proto2.User getUser();
  /**
   * <code>.trojan.api.User user = 1;</code>
   */
  com.spw.proto2.UserOrBuilder getUserOrBuilder();

  /**
   * <code>.trojan.api.Traffic traffic_total = 2;</code>
   */
  boolean hasTrafficTotal();
  /**
   * <code>.trojan.api.Traffic traffic_total = 2;</code>
   */
  com.spw.proto2.Traffic getTrafficTotal();
  /**
   * <code>.trojan.api.Traffic traffic_total = 2;</code>
   */
  com.spw.proto2.TrafficOrBuilder getTrafficTotalOrBuilder();

  /**
   * <code>.trojan.api.Speed speed_current = 3;</code>
   */
  boolean hasSpeedCurrent();
  /**
   * <code>.trojan.api.Speed speed_current = 3;</code>
   */
  com.spw.proto2.Speed getSpeedCurrent();
  /**
   * <code>.trojan.api.Speed speed_current = 3;</code>
   */
  com.spw.proto2.SpeedOrBuilder getSpeedCurrentOrBuilder();

  /**
   * <code>.trojan.api.Speed speed_limit = 4;</code>
   */
  boolean hasSpeedLimit();
  /**
   * <code>.trojan.api.Speed speed_limit = 4;</code>
   */
  com.spw.proto2.Speed getSpeedLimit();
  /**
   * <code>.trojan.api.Speed speed_limit = 4;</code>
   */
  com.spw.proto2.SpeedOrBuilder getSpeedLimitOrBuilder();

  /**
   * <code>int32 ip_current = 5;</code>
   */
  int getIpCurrent();

  /**
   * <code>int32 ip_limit = 6;</code>
   */
  int getIpLimit();
}
